version = 0.1

[default.deploy.parameters]
stack_name = "surfingpal-api-http"
s3_prefix = "surfingpal-api-http"
parameter_overrides = "Stage=\"dev\""
confirm_changeset = false
resolve_s3 = true
region = "us-west-2"
force_upload = true
capabilities = "CAPABILITY_IAM"

[prod.deploy.parameters]
stack_name = "surfingpal-api-http"
s3_prefix = "surfingpal-api-http"
parameter_overrides = "Stage=\"prod\""
confirm_changeset = true
resolve_s3 = true
region = "us-west-2"
force_upload = true
capabilities = "CAPABILITY_IAM"
