version = 0.1

[default.deploy.parameters]
stack_name = "layer-pandas-numpy"
resolve_s3 = true
s3_prefix = "layer-pandas-numpy"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
